lines:
    line1:
        start: [0,0]
        end: [0,6]
        angle: 0
    line2:
        start: [0,6]
        end: [6,6]
        angle: -1.57079632679
    line3:
        start: [6,6]
        end: [6,0]
        angle: 3.14159265359
    line4:
        start: [6,0]
        end: [0,0]
        angle: 1.57079632679