lines:
    line1:
        start: [-2.85,-3]
        end: [-2.83, 3]
        angle: 0
    line2:
        start: [-2.83, 3]
        end: [2.83, 3]
        angle: -1.57079632679
    line3:
        start: [2.83, 3]
        end: [2.83, -3]
        angle: 3.14159265359
    line4:
        start: [2.83, -3]
        end: [-2.83, -3]
        angle: 1.57079632679