lines:
    line1:
        start: [-3,-3]
        end: [-3, 3]
        angle: 0
    line2:
        start: [-3, 3]
        end: [3, 3]
        angle: 4.7123889804
    line3:
        start: [3, 3]
        end: [3, -3]
        angle: 3.14159265359
    line4:
        start: [3, -3]
        end: [-3, -3]
        angle: 1.57079632679