lines:
    line1:
        start: [-7.5,-8]
        end: [-7.5, 8]
        angle: 0
    line2:
        start: [-7.5, 8]
        end: [7.5, 8]
        angle: 4.7123889804
    line3:
        start: [7.5, 8]
        end: [7.5, -8]
        angle: 3.14159265359
    line4:
        start: [7.5, -8]
        end: [-7.5, -8]
        angle: 1.57079632679