lines:
  line1: 
    start: [-3.045, -2.44]
    end: [-3.045, 2.44]
    angle: 0
  line2: 
    start: [-3.045, 2.44]
    end: [3.045, 2.44]
    angle: 4.71239
  line3: 
    start: [3.045, 2.44]
    end: [3.045, -2.44]
    angle: 3.14159
  line4: 
    start: [3.045, -2.44]
    end: [-3.045, -2.44]
    angle: 1.5708
