lines:
    line1:
        start: [-7.5,-7.5]
        end: [-7.5, 7.5]
        angle: 0
    line2:
        start: [-7.5, 7.5]
        end: [7.5, 7.5]
        angle: -1.57079632679
    line3:
        start: [7.5, 7.5]
        end: [7.5, -7.5]
        angle: -3.14159265359
    line4:
        start: [7.5, -7.5]
        end: [-7.5, -7.5]
        angle: 1.57079632679